spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vendors
    username: postgres
    password: PkNLm@#2357
  jpa:
    properties:
      hibernate:
        jdbc:
          "[batch_size]": 1000
  application:
    instance-id: ${random.value}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id}
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URI:http://localhost:8761/eureka}

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true