spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vendors
    username: postgres
    password: PkNLm@#2357
  jpa:
    properties:
      hibernate:
        jdbc:
          "[batch_size]": 1000
  application:
    instance_id: ${random.value}
  cloud:
    consul:
      host: localhost
      port: 5500
      discovery:
        healthCheckPath: ${server.servlet.context-path}/actuator/health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id}}

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus, health
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  level:
    web: info
    "[com.hangout.core]": trace
  # traceID and spanId are predefined MDC keys - we want the logs to include them
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"