spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vendors
    username: postgres
    password: PkNLm@#2357
  jpa:
    properties:
      hibernate:
        jdbc:
          "[batch_size]": 1000
